OAuth to Pleroma fails do to URL-only parameters
Calling `madonctl -i pleroma-instance oauth2 get-url` results in:
```
Error: app registration failed: API query (v1/apps) failed: bad server status code (400): Missing field: client_name. Missing field: redirect_uris.
```
because whatever Pleroma is using for handling OAuth / HTTP won't
parse out parameters from the URL on a `POST` request (which is
fair -- the HTML 5 specs advises that `POST`s should have the
URL encoded parameters in the body, not the URL.)

Fixes #27